# Generated by Django 6.1 on 2026-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('technology', 'Technology'), ('business', 'Business'), ('sports', 'Sports'), ('education', 'Education'), ('entertainment', 'Entertainment')], db_index=True, default='entertainment', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField()),
                ('available_tickets', models.PositiveIntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date', 'time'],
            },
        ),
    ]
